# Generated by Django 4.1 on 2023-01-03 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_news_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'оголошення', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=1024, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_of_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 16, 53, 20, 765694, tzinfo=datetime.timezone.utc), verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_content',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Назва'),
        ),
    ]
