# Generated by Django 4.1 on 2023-01-04 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_of_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 11, 28, 19, 228490, tzinfo=datetime.timezone.utc), verbose_name='Дата публікації'),
        ),
    ]
