# Generated by Django 4.1 on 2023-01-06 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('news', '0006_alter_news_date_of_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_news', to='games.tournament', verbose_name='Турнір:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_of_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 12, 52, 18, 282172, tzinfo=datetime.timezone.utc), verbose_name='Дата публікації'),
        ),
    ]
