# Generated by Django 4.1 on 2023-01-06 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_tournament_alter_news_date_of_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_of_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 13, 47, 14, 802102, tzinfo=datetime.timezone.utc), verbose_name='Дата публікації'),
        ),
    ]
