# Generated by Django 4.1 on 2023-01-15 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_date_of_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_of_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 11, 37, 14, 560341, tzinfo=datetime.timezone.utc), verbose_name='Дата публікації'),
        ),
    ]
