# Generated by Django 4.1 on 2023-01-04 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='Гравець', to=settings.AUTH_USER_MODEL, verbose_name='Гравці'),
        ),
    ]
