# Generated by Django 4.1 on 2023-04-04 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("team", "0002_alter_team_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="players",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="player",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Гравці",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="coach",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Тренер",
            ),
        ),
    ]
