# Generated by Django 4.1 on 2023-01-06 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_playerstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistic',
            name='defence',
            field=models.IntegerField(default=0, null=True, verbose_name='Успішних захистів'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='games',
            field=models.IntegerField(default=0, null=True, verbose_name='Ігри'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_stat', to=settings.AUTH_USER_MODEL, verbose_name='Гравець'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='points',
            field=models.IntegerField(default=0, null=True, verbose_name='Зароблено пунктів'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Рік статистики'),
        ),
    ]
