# Generated by Django 4.1 on 2023-04-07 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_customuser_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstatistic",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="player_stat",
                to=settings.AUTH_USER_MODEL,
                verbose_name="player_stat",
            ),
        ),
    ]
