# Generated by Django 4.1 on 2023-04-09 10:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_alter_playerstatistic_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 9, 10, 6, 11, 40681, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата народження",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playerstatistic",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="player_stat",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Гравець",
            ),
        ),
    ]
