# Generated by Django 4.1 on 2023-01-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_alter_team_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=128, verbose_name='Назва турніру')),
                ('date_of_start', models.DateField(verbose_name='Дата початку')),
                ('date_of_end', models.DateField(verbose_name='Дата кінця')),
                ('teams', models.ManyToManyField(blank=True, null=True, related_name='teams_of_tournament', to='team.team', verbose_name='Команди - учасники')),
            ],
            options={
                'verbose_name': 'турнір',
                'verbose_name_plural': 'Турніри',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_place', models.CharField(max_length=128, verbose_name='Місце проведення')),
                ('store', models.CharField(max_length=64, null=True, verbose_name='Рахунок')),
                ('date_of_game', models.DateTimeField(verbose_name='Дата проведення')),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1', to='team.team', verbose_name='Команда 1')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2', to='team.team', verbose_name='Команда 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.tournament', verbose_name='Турнір(Назва турніру чи товариська гра)')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='team.team', verbose_name='Переможець')),
            ],
            options={
                'verbose_name': 'гру',
                'verbose_name_plural': 'Ігри',
            },
        ),
    ]
