# Generated by Django 4.1 on 2023-01-06 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_alter_team_players'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('statement_id', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coach_statements', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_statements', to='team.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_statements', to='games.tournament')),
            ],
            options={
                'verbose_name': 'заяву',
                'verbose_name_plural': 'Заяви',
            },
        ),
    ]
