# Generated by Django 4.1 on 2023-01-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не розглянута'), (1, 'Розглянута')], default=0, verbose_name='Статус заяви'),
        ),
    ]
