# Generated by Django 4.1 on 2023-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_alter_statement_coach_alter_statement_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="set_first_team",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="set_second_team",
            field=models.IntegerField(default=0),
        ),
    ]
